config/routes.rb
Rails.application.routes.draw do
 resources :wikis
  resources :charges, only: [:new, :create]

  devise_for :users
  
  resources :users do
    member do
      post :downgrade
    end
  end
  
  resources :wikis do
   post '/create_collaborator' => 'wikis#create_collaborator', as: :create_collaborator
   delete '/destroy_collaborator' => 'wikis#destroy_collaborator', as: :destroy_collaborator
  end
 
  get 'about' => 'welcome#about'
  root 'welcome#index'
end

app/models/amount.rb
class Amount < ActiveRecord::Base
  
  def self.default 
    return 15_00
  end
end

app/models/collaboration.rb
class Collaboration < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :confirmable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :authentication_keys => [:email]
         
  has_many :collaborations
  has_many :collaborating_wikis, through: :collaborations, source: :wiki
  has_many :wikis  
  
  after_initialize :set_default_role, :if => :new_record?
  enum role: [:standard, :admin, :premium]

  private
  
  def set_default_role
    self.role ||= :standard
  end
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  
  has_many :collaborations
  has_many :collaborators, through: :collaborations, source: :user #-> { distinct }
  belongs_to :user

  default_scope { order('created_at DESC') }
  scope :visible_to, -> (user) { user ? where(private: false) : 'There was an error.' }
  
  def markdown_title
    markdown_to_html(self.title)
  end

  def markdown_body
    markdown_to_html(self.body)
  end
  
  def public?
    !private?
  end
  
  def markdown_to_html(markdown)
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true, autolink: true, no_intra_emphasis: true, highlight: true, strikethrough: true, superscript: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render markdown).html_safe
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  
  protect_from_forgery with: :exception
  
  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to root_url, alert: exception.message
  end
end

app/controllers/charges_controller.rb
require 'amount'
class ChargesController < ApplicationController
  after_action :upgrade_user_role, only: :create
  
  # Creates a Stripe Customer object, for associating
  # with the charge
  
  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "BigMoney Membership - #{current_user.name}",
      amount: Amount.default
    }
  end
  def create
    customer = Stripe::Customer.create(
    email: current_user.email,
    card: params[:stripeToken]
  )
 
  # Where the real magic happens
  charge = Stripe::Charge.create(
    customer: customer.id, # -- this is NOT the user_id in your app
    amount: Amount.default,
    description: "BigMoney Membership - #{current_user.email}",
    currency: 'usd'
  )
 
  flash[:notice] = "Thanks for upgrading your service, #{current_user.email}! You have unlocked the capability of creating private Wikis."
  redirect_to root_path(current_user) # or wherever
  upgrade_user_role
 
  # Stripe will send back CardErrors, with friendly messages
  # when something goes wrong.
  # This `rescue block` catches and displays those errors.
  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to new_charge_path
  end
  
  private
  
  def upgrade_user_role
    current_user.update_attribute(:role, 'premium')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    if current_user.present?
      @user = params[:id] ? User.find(params[:id]) : current_user
    else
      redirect_to root_path
    end
  end

  def index
    @users = User.all  
  end

  def new
    @user = User.new
  end
  
  def downgrade
    @user = current_user
    @user.update_attribute(:role, "standard")
    @wikis = @user.wikis.where(user_id: @user.id).all
    
    @wikis.each do |wiki|
      wiki.update_attribute(:private, "false")
      wiki.collaborators = []
    end
    if @user
      flash[:notice] = "You've been downgraded to #{@user.role}. Your private wikis are now public."
      redirect_to :root
    else
      flash[:error] = "There was an error downgrading your account. Please try again."
      redirect_to :back
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
require 'will_paginate/array'

class WikisController < ApplicationController
  include ApplicationHelper
  
  before_action :authenticate_user!
  
  def index
    @wikis = policy_scope(Wiki).paginate(page: params[:page], per_page: 10)
  end

  def show
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end
  
  def create
    @user = current_user
    @wiki = @user.wikis.build(wiki_params)
    authorize @wiki

    if @wiki.save
      flash[:notice] = "Wiki titled #{@wiki.title} was saved."
      redirect_to @wiki
    else
      flash.now[:error] = "There was an error saving the wiki titled #{@wiki.title}. Please try again."
      render :new
    end
  end

  def edit
    @users = User.all
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end
  
  def update 
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    @wiki.user_ids = params[:wiki][:user_ids] if params[:wiki][:user_ids].present?
 
    if @wiki.update_attributes(wiki_params)
      flash[:notice] = "Wiki titled #{@wiki.title} was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki titled #{@wiki.title}. Please try again."
      render :edit
    end
  end
  
  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki
 
    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:error] = "There was an error deleting the wiki titled \"#{@wiki.title}\"."
      render :show
    end
  end
  
  def create_collaborator
    @wiki = Wiki.find(params[:wiki_id])
    @user = User.find(params[:user_id])
    
    if @user
      @wiki.collaborators << (@user)
      flash[:notice] = "#{@user.email} successfully added as collaborator to wiki."
      redirect_to @wiki 
    else
      flash[:error] = "There was an error adding #{@user.email} as collaborator to wiki."
      redirect_to :edit
    end  
  end
  
  def destroy_collaborator
    @wiki = Wiki.find(params[:wiki_id])
    @user = User.find( params[:user_id])
    @collaborator = @wiki.collaborators.find(@user.id)
    
    if @collaborator 
      @wiki.collaborators.destroy(@collaborator)
      flash[:notice] = "#{@user.email} was successfully removed as collaborator to wiki."
      redirect_to @wiki
    else
      flash[:error] = "Error. Could not remove #{@user.email} as collaborator to wiki."
      redirect_to @wiki
    end 
  end
  
  private
  
  def wiki_params
    params.require(:wiki).permit(:id, :title, :body, :user_id, :private)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
  def authorized_collaborators?(wiki)
    wiki.collaborators.include?(current_user) || current_user.admin? || current_user.id == wiki.user_id
  end
  
  def owner_of_wiki?(wiki)
    current_user.admin? || current_user.id == @wiki.user_id
  end
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <h4>Click the button!</h4>
  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" 
  data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" 
  data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocipedia</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container-fluid navbar">
      <div class= "row">
        <ul class="nav nav-tabs pull-left col-xs-12">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Wikis", wikis_path %></li>
          <li><%= link_to "Users", users_path %></li>
        
          <% if user_signed_in? %>
            <li class= "pull-right"><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li> 
            <li class= "pull-right"><%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li> 
            <% if current_user.standard? %>
              <li class= "pull-right"><%= link_to 'Upgrade to Premium?', new_charge_path, :class => 'navbar-link' %></li>
            <% elsif current_user.premium? %>
              <li class= "pull-right"><%= link_to "Downgrade to Standard", downgrade_user_path(current_user), method: :post, :class => 'navbar-link', data: { confirm: 'Are you sure you want to downgrade your account?' }  %>
              </li>
            <% end %>  
          <% else %>
            <li class= "pull-right"><%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %></li> 
            <li class= "pull-right"><%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %></li> 
            <li class= "pull-right"><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li>
          <% end %>
        </ul>
        <div class= "text-right">
          <% if user_signed_in? %>
            <h5><small>Signed in as: </small><strong><%= current_user.email %></strong></h5>
          <% end %>
        </div>
      </div>
    </div>
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>  
    <%= yield %> 
  </body>
</html>

app/views/users/index.html.erb
<div class= "container-fluid">
  <div class="row">
    <h1 class="text-center"> Blocipedia Users </h1>
  <div class= "row center-block" style= "width: 75%">
    <div>
      <table class= "table table-striped " >
        <thead>
          <tr>
            <th class= "">User</th>
            <th class= "text-center">Collaborating wikis</th>
            <th class= "text-center">Role</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td class= "text-left text-primary"><%= user.email %></td>
              <td class= "text-center text-danger"><%= user.collaborating_wikis.count %></td>
              <td class= "text-center text-success"><%= user.role.capitalize %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
</div>

app/views/users/new.html.erb
<h2> Sign Up </h2>

<div class="row">
  <div class="col-md-8">
    <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
        <div class="alert alert-danger">
          <h4> <%= pluralize(@user.errors.count, "error") %>. </h4>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li> <%= msg %> </li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= form_group_tag(@user.errors[:name]) do %>
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true, class: 'form-control', placeholder: "Enter name" %>
      <% end %>

      <%= form_group_tag(@user.errors[:email]) do %>
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control', placeholder: "Enter email" %>
      <% end %>

      <%= form_group_tag(@user.errors[:password]) do %>
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control', placeholder: "Enter password" %>
      <% end %>

      <%= form_group_tag(@user.errors[:password_confirmation]) do %>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Enter password confirmation" %>
      <% end %>

      <div class="form-group">
        <%= f.submit "Sign Up", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/welcome/about.html.erb
<div class= "center-block" style= "width: 75%">
  <h1 class= "text-center">The history of the Wiki</h1>
  <blockquote>
    <p>WikiWikiWeb was the first wiki. Ward Cunningham started developing WikiWikiWeb in Portland, Oregon, in 1994, and installed 
    it on the Internet domain c2.com on March 25, 1995. It was named by Cunningham, who remembered a Honolulu International Airport counter 
    employee telling him to take the "Wiki Wiki Shuttle" bus that runs between the airport's terminals. According to Cunningham, 
    "I chose wiki-wiki as an alliterative substitute for 'quick' and thereby avoided naming this stuff quick-web."</p>
    <p>Cunningham was, in part, inspired by Apple's HyperCard, which he had used. Hypercard, however, was single-user. Apple had designed 
    a system allowing users to create virtual "card stacks" supporting links among the various cards. Cunningham developed Vannevar Bush's 
    ideas by allowing users to "comment on and change one another's text." Cunningham says his goals were to link together the 
    experiences of multiple people to create a new literature to document programming patterns, and to harness people's natural desire to 
    talk and tell stories with a technology that would feel comfortable to those not used to "authoring".</p>
    <p>Wikipedia became the most famous wiki site, entering the top ten most popular websites in 2007. In the early 2000s (decade), wikis 
    were increasingly adopted in enterprise as collaborative software. Common uses included project communication, intranets, and documentation, 
    initially for technical users. Some companies use wikis as their only collaborative software and as a replacement for static intranets, and 
    some schools and universities use wikis to enhance group learning. There may be greater use of wikis behind firewalls than on the public Internet. 
    On March 15, 2007, the word wiki was listed in the online Oxford English Dictionary.</p>
    <footer>Information provided by <cite title="Wikipedia">Wikipedia</cite></footer>
  </blockquote>
</div>

app/views/welcome/index.html.erb
<div class= "center-block" style= "width: 75%">
  <h1 class= "text-center">Welcome to Blocipedia</h1>
  <blockquote>
    <p>A wiki (wik-ee) is a website that provides collaborative modification of its content and structure 
    directly from the web browser. In a typical wiki, text is written using a simplified markup language 
    (known as "wiki markup") and often edited with the help of a rich-text editor. A wiki is run using 
    wiki software, otherwise known as a wiki engine. There are dozens of different wiki engines in use, 
    both standalone and part of other software, such as bug tracking systems. Some wiki engines are open 
    source, whereas others are proprietary. Some permit control over different functions (levels of access); 
    for example, editing rights may permit changing, adding or removing material. Others may permit access 
    without enforcing access control. Other rules may also be imposed to organize content. A wiki engine is 
    a type of content management system, but it differs from most other such systems, including blog software, 
    in that the content is created without any defined owner or leader, and wikis have little implicit structure, 
    allowing structure to emerge according to the needs of the users.</p>
    <ul>
      <li>A wiki invites all users—not just experts—to edit any page or to create new pages within the wiki Web site, 
      using only a standard "plain-vanilla" Web browser without any extra add-ons.</li>
      <li>Wiki promotes meaningful topic associations between different pages by making page link creation intuitively easy 
      and showing whether an intended target page exists or not.</li>
      <li>A wiki is not a carefully crafted site created by experts and professional writers, and designed for casual visitors. 
      Instead, it seeks to involve the typical visitor/user in an ongoing process of creation and collaboration that 
      constantly changes the website landscape.</li>
    </ul>
    <p>A wiki enables communities of editors and contributors to write documents collaboratively. All that people require 
    to contribute is a computer, Internet access, a web browser and a basic understanding of a simple markup language 
    (e.g., HTML). A single page in a wiki website is referred to as a "wiki page", while the entire collection of pages, 
    which are usually well-interconnected by hyperlinks, is "the wiki". A wiki is essentially a database for creating, 
    browsing, and searching through information. A wiki allows non-linear, evolving, complex and networked text, while 
    also allowing for editor argument, debate and interaction regarding the content and formatting. A defining 
    characteristic of wiki technology is the ease with which pages can be created and updated. Generally, there is no 
    review by a moderator or gatekeeper before modifications are accepted and thus lead to changes on the website. Many 
    wikis are open to alteration by the general public without requiring registration of user accounts. Many edits can 
    be made in real-time and appear almost instantly online. However, this feature facilitates abuse of the system. 
    Private wiki servers require user authentication to edit pages, and sometimes even to read them. Maged N. Kamel Boulos, 
    Cito Maramba and Steve Wheeler write that the open wikis produce a process of Social Darwinism. " 'Unfit' sentences and 
    sections are ruthlessly culled, edited and replaced if they are not considered 'fit', which hopefully results in the 
    evolution of a higher quality and more relevant page. While such openness may invite 'vandalism' and the posting of untrue 
    information, this same openness also makes it possible to rapidly correct or restore a 'quality' wiki page.
    </p>
    <footer>Information provided by <cite title="Wikipedia">Wikipedia</cite></footer>
  </blockquote>
</div>

app/views/wikis/_form.html.erb
<div class = "form-contain center-block">
  <%= form_for @wiki do |f| %>
    <div class="form-group has-success has-feedback text-primary text-left">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control focus', placeholder: "Enter wiki title" %>
    </div>
    <% if @wiki.created_at.nil? %>
      <% if current_user.role == "premium" || current_user.role == "admin" %>
        <div class="form-group text-primary text-left">
          <%= f.label :private %>
          <%= f.check_box :private %> 
        </div>
      <% end %>
    <% else %>
      <% if owner_of_wiki?(@wiki) && current_user.role != "standard" %>
        <div class="form-group text-primary text-left">
          <%= f.label :private %>
          <%= f.check_box :private %> 
        </div>
      <% end %>
    <% end %>
    <div class="form-group has-success has-feedback text-primary text-left">
      <%= f.label :body %>
      <%= f.text_area :body, rows: 8, class: 'form-control focus', placeholder: "Enter wiki body" %>
    </div>
    <div class="form-group has-success has-feedback text-center">
      <%= f.submit "Save", class: 'btn btn-success' %>
      <% unless @wiki.created_at.nil? && owner_of_wiki?(@wiki) %>
        <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this wiki?' } %> 
      <% end %>
    </div>
  <% end %>
</div>

app/views/wikis/_wiki.html.erb
<table class="table" style= "margin-top: 20px">
	<thead>
	  <tr class= "bg-success">
		<th>Email</th>
		<th>Add Collaborator</th>
		<th>Delete Collaborator</th>
	  </tr>
	</thead>
	<tbody>	
		<div class="field">
		  <% @users.each do |user| %>
			  <div class="form-group">
			    <% if owner_of_wiki?(@wiki) %>
			      <% unless user.admin? || user.id == @wiki.user_id %>
			        <tr>
			          <td><%= user.email %></td>
			          <% if @wiki.collaborators.include?(user) %>
			            <td></td>
			            <td><%= button_to "Delete Collaborator", wiki_destroy_collaborator_path(@wiki.id, @user), method: :delete, params: { user_id: user.id}, class: "btn btn-danger" %></td>
			          <% else %>
			            <td><%= button_to "Add Collaborator", wiki_create_collaborator_path(@wiki.id), params: { user_id: user.id}, class:"btn btn-primary" %></td>
			            <td><%= button_to "Delete Collaborator", wiki_destroy_collaborator_path(@wiki.id, @user), method: :delete, params: { user_id: user.id}, class: "btn btn-danger" %></td>	
			          <% end %>
			        </tr>
			      <% end %>
			    <% end %>
			  </div>
		  <% end %>
		</div>
	</tbody>
</table> 

app/views/wikis/edit.html.erb
<div class= "wiki-edit-container">
  <div class= "wiki-small">
    <div class= "center-block edit-form">
      <h4 class= "text-center text-primary"><b class= "text-danger">Edit: </b><%= @wiki.markdown_title %></h4>
      <div class="row">
        <div class="col-xl-4 edit-text text-warning ">
          <p>A website that allows collaborative editing of its content and structure by its users</p>
          <ul class= "edit-list">
            <li>Wikis permit asynchronous communication and group collaboration
             across the Interne</li>
            <li> The term "Wiki" is used as an alliterative substitute for quick</li>
          </ul>
        </div>
        <div class="col-xl-4">
          <%= render partial: 'wikis/form' %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xl-4">
    <% if owner_of_wiki?(@wiki) && @wiki.user.role != "standard" %>
      <%= render partial: 'wikis/wiki', locals: { wiki: @wiki, user: @user } %>
    <% end %>
  </div>
</div>

app/views/wikis/index.html.erb
<div class= "container wiki-main ">
  <div class= "paginate">
    <%= will_paginate @wikis %>
  </div>
  <div class= "row center-block wiki-container" style= "width: 75%">
    <div class= "header">
      <h1 class= "text-center wiki-title"><strong>All Wikis</strong></h1>
    </div>
    <div class ="wiki-titles" style= "margin-top: 20px">
      <% @wikis.each do |wiki| %>
        <div class="media">
          <div class="media-body">
            <h4 class="media-heading text-center">
            <%= link_to wiki.markdown_title, wiki %>
            </h4>
            <small class= "text-center text-warning">
              <%= wiki.markdown_body %>
            </small>  
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class= "text-center center-block new-wiki">
    <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-primary btn-block'%>
  </div>
  <div class= "paginate">
    <%= will_paginate @wikis %>
  </div>
</div>

app/views/wikis/new.html.erb
<div class= "wiki-new-container">
  <div class= "wiki-new">
    <div class= "center-block new-form">
      <h1 class= "text-center text-heading">New Wiki</h1>
      <div class="row">
        <div class="col-xl-6 new-text text-center text-warning ">
          <p class= "text-center">A website that allows collaborative editing of its content and structure by its users</p>
          <ul class= "new-list text-center">
            <li>Wikis permit asynchronous communication and group collaboration
             across the Interne</li>
            <li> The term "Wiki" is used as an alliterative substitute for quick</li>
          </ul>
        </div>
        <div class="col-xl-6 new-wiki-form">
          <%= render partial: 'wikis/form' %>
        </div>
      </div>
    </div>
  </div>
  <div >
</div>

app/views/wikis/show.html.erb
<div class= "wiki-show-container">
  <div class= "wiki-show">
    <div class= "back-button center-block">
      <%= link_to "Back to wikis", wikis_path %>
    </div>
    <div class= "col-xl-12 center-block show-info" style= "width: 60%">
      <h2 class= "text-center text-primary"> <%= @wiki.markdown_title %> </h2>
      <div class= "text-center show-body">
        <p class= "center-align text-warning"><%= @wiki.markdown_body %></p>
        <small class= "text-center text-success">
          <i>Wiki submitted <%= time_ago_in_words(@wiki.created_at) %> ago.<br/> Last updated on <%= @wiki.updated_at%>.</i><br/>
        </small>
      </div>
      <div class= "wiki-update text-center" style= "margin-top: 25px">
        <% if owner_of_wiki?(@wiki) && @wiki.user.role != "standard" %>
          <%= link_to "Add/Remove Collaborator", edit_wiki_path(@wiki), class: 'btn btn-success' %>
        <% end %>
        <% if owner_of_wiki?(@wiki) %>
          <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this wiki?' } %> 
        <% end %>
        <% if authorized_collaborators?(@wiki) %>
          <%= link_to "Edit Wiki", edit_wiki_path(@wiki), class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
  <div class= "show-collab">
    <% unless @wiki.collaborators.empty? || current_user.role == "standard" %>
      <div class= "collab-show" >
        <table class="table">
          <thead>
			       <tr class= "bg-success">
				      <th class= "" style= "padding: 0px"><h4>Collaborators for this Wiki</h4></th>
				      <th class= "text-right" style= "padding: 0px"><h4>Delete Collaborator</h4></th>
				    </tr>
		      </thead>
		      <tbody>
            <% @wiki.collaborators.each do |collaborator| %>
              <tr>
                <td class= "text-warning"><strong><%= collaborator.email %></strong></td>
                <% if owner_of_wiki?(@wiki) %>
                  <td><%= button_to "Delete Collaborator", wiki_destroy_collaborator_path(@wiki.id, @user), method: :delete, params: { user_id: collaborator.id }, class: "btn btn-danger pull-right" %></td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    <% end %>
  </div>
</div>
  


  